import numpy as np

# seed
SEED = 9999

# video
MAX_VIDEO_DURATION = 100.0
MIN_VIDEO_DURATION = 1.0
EMB_DIM = 10

# user state
MAX_CUM_NEXT_TIME = 9 * 24 * 60
MAX_HIST_CLICK_TAG_NUM = 50
STATIC_FEATURE_DIM = 10
DYNAMIC_FEATURE_DIM = 10

# user response
MAX_NEXT_TIME = 1440.0

SCORE_WEIGHT_MATRIX = np.random.normal(size=(10, 20))
